
# EMA hyperparameters:
use_ema: false
decay: 0.995

# Scheduler hyperparameters:
scheduler_kwargs:
    num_train_timesteps: 50
    beta_schedule: "scaled_linear"
    beta_start: 0.0001
    beta_end: 0.2
    clip_sample: false
    

# Model hyperparameters:
config : 
    
    # Base PriSTI hyperparameters
    layers: 4
    channels: 64
    nheads: 8
    diffusion_embedding_dim: 128
    is_adp: true
    proj_t: 64
    is_cross_t: true
    is_cross_s: true
    adj_file: metr-la, 
    side_dim: 144
    scale_window_factor: 2
    batch_size: 4


# Optimizer params:


