# EMA hyperparameters:
use_ema: false
decay: 0.995

# Scheduler hyperparameters:
scheduler_kwargs:
    num_train_timesteps: 50
    beta_schedule: "scaled_linear"
    beta_start: 0.0001
    beta_end: 0.5
    clip_sample: false
    
# Optimizer params:


